version: '3.9'

services:

    phmoney_azure:
        image: phalouvas/phmoney_app:0.0.6
        hostname: azure
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}azure.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}azure.rule=Host(`${COMPOSE_PROJECT_NAME}_azure.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}azure.service=${COMPOSE_PROJECT_NAME}azure"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}azure.loadbalancer.server.port=80"
        environment:
            - PHMONEY_ENV=azure
            - PHMONEY_VERSION=master
