version: '3.9'

services:

    phmoney:
        container_name: ${COMPOSE_PROJECT_NAME}_${COMPOSE_SUB_DOMAIN}
        image: phalouvas/laravel:php8.0-nginx-develop
        hostname: ${COMPOSE_SUB_DOMAIN}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}${COMPOSE_SUB_DOMAIN}.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}${COMPOSE_SUB_DOMAIN}.rule=Host(`${COMPOSE_SUB_DOMAIN}.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}${COMPOSE_SUB_DOMAIN}.service=${COMPOSE_PROJECT_NAME}${COMPOSE_SUB_DOMAIN}1"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}${COMPOSE_SUB_DOMAIN}1.loadbalancer.server.port=80"
        environment:
            - PHCOMM_ENV=local
            - PHCOMM_BUILD_ASSETS=false
            - PHCOMM_SUPERVISOR=false
        volumes:
            - ../phmoney_app/:/var/www/html//:rw
            - ../docker/:/home/docker//:rw

networks:
    default:
        name: ${COMPOSE_NETWORK_NAME}-local-net
        driver: bridge
