version: '3.9'

services:

    phmoney_azure:
        build: ./nginx
        image: phalouvas/phmoney_app:0.0.2
        restart: always
        environment:
            - PHMONEY_ENV=azure
        volumes:
            - ../phmoney_app/:/home/code/
            - ../docker/:/home/docker/

    phmoney_local:
        container_name: ${COMPOSE_PROJECT_NAME}_app
        build: ./nginx
        image: phalouvas/phmoney_app:local
        hostname: app
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}app.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}app.rule=Host(`${COMPOSE_PROJECT_NAME}_app.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}app.service=${COMPOSE_PROJECT_NAME}app"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}app.loadbalancer.server.port=80"
        environment:
            - PHMONEY_ENV=local
        volumes:
            - ../phmoney_app/:/var/www/html//:rw
            - ../docker/:/home/docker//:rw

    phmoney_assets:
        container_name: ${COMPOSE_PROJECT_NAME}_assets
        build: ./assets
        hostname: assets
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}assets.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}assets.rule=Host(`${COMPOSE_PROJECT_NAME}_assets.${COMPOSE_BASE_DOMAIN}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}assets.service=${COMPOSE_PROJECT_NAME}assets"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}assets.loadbalancer.server.port=80"
        volumes:
            - ../phmoney_assets/dist/:/var/www/html/:rw

networks:
    default:
        name: ${COMPOSE_NETWORK_NAME}-local-net
        driver: bridge
