version: '3.9'

services:

    phmoney:
        image: phalouvas/laravel:php8.0-nginx
        restart: always
        environment:
            - PHCOMM_ENV=production
            - PHCOMM_BUILD_ASSETS=false
            - PHCOMM_SUPERVISOR=false
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site/wwwroot/code:/home/code
            - ${WEBAPP_STORAGE_HOME}/site/wwwroot/docker/:/home/docker
